# Generated by Django 3.2.12 on 2022-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0002_group_groupchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('thread_name', models.CharField(max_length=50)),
                ('message_id', models.IntegerField()),
            ],
        ),
    ]
